// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3GUK7Op7QT0bQ63hjqjlwnW4tnhz-xA',
    appId: '1:761670154656:web:3990c48e1fcb4aafdcccc5',
    messagingSenderId: '761670154656',
    projectId: 'atteventify-c7271',
    authDomain: 'atteventify-c7271.firebaseapp.com',
    storageBucket: 'atteventify-c7271.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZTzDsyx6Fgihe1v4tZOfWSqqFYQ_yXnk',
    appId: '1:761670154656:android:354a1d84e2fea0e7dcccc5',
    messagingSenderId: '761670154656',
    projectId: 'atteventify-c7271',
    storageBucket: 'atteventify-c7271.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF3GUK7Op7QT0bQ63hjqjlwnW4tnhz-xA',
    appId: '1:761670154656:web:0ead8b321770f06adcccc5',
    messagingSenderId: '761670154656',
    projectId: 'atteventify-c7271',
    authDomain: 'atteventify-c7271.firebaseapp.com',
    storageBucket: 'atteventify-c7271.appspot.com',
  );
}
